[package]
name = "rolr"
version = "0.0.0-dev" # patched by github actions
edition = "2021"
description = "Host role manager built on top of ansible"
readme = "README.md"
license = "GPL-3"
authors = ["thorou"]
repository = "https://github.com/thorio/rolr"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.9", features = ["derive"] }
console = "0.15.8"
dialoguer = { version = "0.11.0", default-features = false }
itertools = "0.14.0"
log = "0.4.22"
stderrlog = "0.6.0"
sys-info = "0.9.1"

[profile.release]
panic = "abort"
opt-level = "s"
strip = true
lto = true

[lints.rust]
non_ascii_idents = "forbid"
noop_method_call = "warn"
single_use_lifetimes = "warn"
unused_crate_dependencies = "warn"
unused_lifetimes = "deny"
unused_qualifications = "warn"

[lints.clippy]
cognitive_complexity = "warn"
dbg_macro = "warn"
empty_structs_with_brackets = "warn"
equatable_if_let = "warn"
explicit_iter_loop = "warn"
match_wildcard_for_single_variants = "warn"
or_fun_call = "warn"
question_mark = "warn"
redundant_closure_for_method_calls = "warn"
semicolon_if_nothing_returned = "warn"
unwrap_used = "warn"
use_self = "warn"
used_underscore_binding = "warn"
wildcard_imports = "warn"
missing_panics_doc = "warn"
