[package]
name = "rolr"
version = "0.0.0" # patched by github actions
edition = "2021"
description = "host role manager built on top of ansible"
readme = "README.md"
license = "GPL-3.0"
authors = ["thorou"]
repository = "https://github.com/thorio/rolr"

[package.metadata.deb]
maintainer = "thorou <thorio.git@gmail.com>"
section = "utils"
priority = "extra"
depends = []

[package.metadata.arch]
maintainer = "thorou <thorio.git@gmail.com>"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.9", features = ["derive"] }
console = "0.15.8"
dialoguer = { version = "0.11.0", default-features = false }
itertools = "0.13.0"
lazy_static = "1.5.0"
log = "0.4.22"
regex = "1.10.5"
stderrlog = "0.6.0"
sys-info = "0.9.1"

[profile.release]
panic = "abort"
opt-level = "s"
strip = true
lto = true
