[package]
name = "rolr"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
lto = true

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.19", features = ["derive"] }
console = "0.15.7"
itertools = "0.11.0"
lazy_static = "1.4.0"
regex = "1.9.1"
sys-info = "0.9.1"
