# everything below was generated by clap_complete
# this is missing role completions, feel free to open a PR

# Print an optspec for argparse to handle cmd's options that are independent of any subcommand.
function __fish_rolr_global_optspecs
	string join \n v/verbose q/quiet h/help V/version
end

function __fish_rolr_needs_command
	# Figure out if the current invocation already has a command.
	set -l cmd (commandline -opc)
	set -e cmd[1]
	argparse -s (__fish_rolr_global_optspecs) -- $cmd 2>/dev/null
	or return
	if set -q argv[1]
		# Also print the command, so this can be used to figure out what it is.
		echo $argv[1]
		return 1
	end
	return 0
end

function __fish_rolr_using_subcommand
	set -l cmd (__fish_rolr_needs_command)
	test -z "$cmd"
	and return 1
	contains -- $cmd[1] $argv
end

complete -c rolr -n "__fish_rolr_needs_command" -s v -l verbose -d 'Increase logging verbosity'
complete -c rolr -n "__fish_rolr_needs_command" -s q -l quiet -d 'Decrease logging verbosity'
complete -c rolr -n "__fish_rolr_needs_command" -s h -l help -d 'Print help'
complete -c rolr -n "__fish_rolr_needs_command" -s V -l version -d 'Print version'
complete -c rolr -n "__fish_rolr_needs_command" -f -a "add" -d 'Activate roles'
complete -c rolr -n "__fish_rolr_needs_command" -f -a "select" -d 'Activate roles in a TUI menu'
complete -c rolr -n "__fish_rolr_needs_command" -f -a "update" -d 'Update all active roles'
complete -c rolr -n "__fish_rolr_needs_command" -f -a "list" -d 'List available roles'
complete -c rolr -n "__fish_rolr_needs_command" -f -a "run" -d 'Run roles without activating them'
complete -c rolr -n "__fish_rolr_needs_command" -f -a "complete" -d 'Used for shell completions. Not stable!'
complete -c rolr -n "__fish_rolr_needs_command" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c rolr -n "__fish_rolr_using_subcommand add" -s v -l verbose -d 'Increase logging verbosity'
complete -c rolr -n "__fish_rolr_using_subcommand add" -s q -l quiet -d 'Decrease logging verbosity'
complete -c rolr -n "__fish_rolr_using_subcommand add" -s h -l help -d 'Print help'
complete -c rolr -n "__fish_rolr_using_subcommand add" -s V -l version -d 'Print version'
complete -c rolr -n "__fish_rolr_using_subcommand select" -s v -l verbose -d 'Increase logging verbosity'
complete -c rolr -n "__fish_rolr_using_subcommand select" -s q -l quiet -d 'Decrease logging verbosity'
complete -c rolr -n "__fish_rolr_using_subcommand select" -s h -l help -d 'Print help'
complete -c rolr -n "__fish_rolr_using_subcommand select" -s V -l version -d 'Print version'
complete -c rolr -n "__fish_rolr_using_subcommand update" -s v -l verbose -d 'Increase logging verbosity'
complete -c rolr -n "__fish_rolr_using_subcommand update" -s q -l quiet -d 'Decrease logging verbosity'
complete -c rolr -n "__fish_rolr_using_subcommand update" -s h -l help -d 'Print help'
complete -c rolr -n "__fish_rolr_using_subcommand update" -s V -l version -d 'Print version'
complete -c rolr -n "__fish_rolr_using_subcommand list" -s v -l verbose -d 'Increase logging verbosity'
complete -c rolr -n "__fish_rolr_using_subcommand list" -s q -l quiet -d 'Decrease logging verbosity'
complete -c rolr -n "__fish_rolr_using_subcommand list" -s h -l help -d 'Print help'
complete -c rolr -n "__fish_rolr_using_subcommand list" -s V -l version -d 'Print version'
complete -c rolr -n "__fish_rolr_using_subcommand run" -s v -l verbose -d 'Increase logging verbosity'
complete -c rolr -n "__fish_rolr_using_subcommand run" -s q -l quiet -d 'Decrease logging verbosity'
complete -c rolr -n "__fish_rolr_using_subcommand run" -s h -l help -d 'Print help'
complete -c rolr -n "__fish_rolr_using_subcommand run" -s V -l version -d 'Print version'
complete -c rolr -n "__fish_rolr_using_subcommand complete" -s v -l verbose -d 'Increase logging verbosity'
complete -c rolr -n "__fish_rolr_using_subcommand complete" -s q -l quiet -d 'Decrease logging verbosity'
complete -c rolr -n "__fish_rolr_using_subcommand complete" -s h -l help -d 'Print help'
complete -c rolr -n "__fish_rolr_using_subcommand complete" -s V -l version -d 'Print version'
complete -c rolr -n "__fish_rolr_using_subcommand help; and not __fish_seen_subcommand_from add select update list run complete help" -f -a "add" -d 'Activate roles'
complete -c rolr -n "__fish_rolr_using_subcommand help; and not __fish_seen_subcommand_from add select update list run complete help" -f -a "select" -d 'Activate roles in a TUI menu'
complete -c rolr -n "__fish_rolr_using_subcommand help; and not __fish_seen_subcommand_from add select update list run complete help" -f -a "update" -d 'Update all active roles'
complete -c rolr -n "__fish_rolr_using_subcommand help; and not __fish_seen_subcommand_from add select update list run complete help" -f -a "list" -d 'List available roles'
complete -c rolr -n "__fish_rolr_using_subcommand help; and not __fish_seen_subcommand_from add select update list run complete help" -f -a "run" -d 'Run roles without activating them'
complete -c rolr -n "__fish_rolr_using_subcommand help; and not __fish_seen_subcommand_from add select update list run complete help" -f -a "complete" -d 'Used for shell completions. Not stable!'
complete -c rolr -n "__fish_rolr_using_subcommand help; and not __fish_seen_subcommand_from add select update list run complete help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
