use crate::{config, roles::Play};
use anyhow::{anyhow, Result};
use std::io::{BufWriter, Write};
use std::process::exit;
use std::{fs::File, os::unix::process::CommandExt, path::Path, process::Command};

pub fn run_plays(plays: &[Play]) -> Result<()> {
	let playbook_path = config::get_playbook_file();

	if plays.is_empty() {
		return Err(anyhow!("Nothing to do."));
	}

	generate(&playbook_path, plays)
		.map_err(|err| anyhow!("Unable to generate playbook at {playbook_path:?}: {err}"))?;

	run(&playbook_path);
}

fn generate(path: impl AsRef<Path>, plays: &[Play]) -> Result<()> {
	let file = File::create(path)?;
	let mut writer = BufWriter::new(file);

	writeln!(writer, "---")?;
	writeln!(writer, "# This file was automatically generated by rolr")?;

	for play in plays {
		writeln!(writer, "- import_playbook: {}", play.path.display())?;
	}

	Ok(())
}

fn run(path: impl AsRef<Path>) -> ! {
	let err = Command::new("ansible-playbook")
		.current_dir(config::get_config_dir())
		.args([
			"--connection=local",
			"--inventory=localhost,",
			"--limit=localhost",
			&path.as_ref().to_string_lossy(),
			"-K",
		])
		.exec();

	log::error!("{err}");
	log::error!("exec ansible-playbook failed; maybe it isn't installed?");
	exit(1)
}
