use crate::{config, roles::Play};
use anyhow::{anyhow, Result};
use std::{
	fs::{self, File},
	io::{BufWriter, Write},
	os::unix::process::CommandExt,
	path::Path,
	process::Command,
};

#[allow(unused)]
pub fn run_plays(plays: &[Play]) -> Result<()> {
	let playbook_path = config::get_playbook_file();
	generate(&playbook_path, plays)?;
	run(&playbook_path);
}

fn generate(path: impl AsRef<Path>, plays: &[Play]) -> Result<()> {
	fs::create_dir_all(path.as_ref().parent().ok_or(anyhow!(""))?)?;

	let file = File::create(path)?;
	let mut writer = BufWriter::new(file);

	writeln!(writer, "---")?;
	writeln!(writer, "# This file was automatically generated by rolr")?;

	for play in plays {
		writeln!(writer, "- import_playbook: {}", play.path.display())?;
	}

	Ok(())
}

fn run(path: impl AsRef<Path>) -> ! {
	Command::new("ansible-playbook")
		.args(vec![
			"--connection=local",
			"--inventory=localhost,",
			"--limit=localhost",
			path.as_ref().to_str().unwrap(),
			"-K",
		])
		.exec();

	panic!("exec ansible didn't work");
}
