---
# pilgrim

- name: Solanum
  gather_facts: false
  hosts: all
  tasks:
    - name: Campfire
      debug:
        msg: I believe we've reached the end of our journey. All that remains is to collapse the innumerable possibilities before us. Are you ready to learn what comes next?
