name: lint & test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: lint
        run: cargo clippy -- -D warnings

      - name: test
        run: cargo test --verbose
