name: lint & test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: install tools
        run: |
          sudo apt-get install musl-tools -y
          rustup target add x86_64-unknown-linux-musl

      - name: lint
        run: cargo clippy -- -D warnings

      - name: test
        run: cargo test --verbose
