name: publish

on:
  push:
    tags: [ 'v*' ]

jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: install tools
        run: |
          sudo apt-get install musl-tools -y
          rustup target add x86_64-unknown-linux-musl
          cargo install cargo-deb

      - name: patch project version
        run: |
          tag=$(echo ${{ github.ref }} | grep -Po '(?<=^refs/tags/v).*')
          version=$tag+${GITHUB_SHA:0:8}
          sed -i "0,/version/{s/0.0.0/$version/}" Cargo.toml

      - name: build standalone binary
        run: cargo build --release && cp target/x86_64-unknown-linux-musl/release/rolr ./rolr-x86_64 && xz rolr-x86_64

      - name: package deb
        run: cargo deb --target x86_64-unknown-linux-musl && cp target/x86_64-unknown-linux-musl/debian/rolr*.deb ./rolr-x86_64.deb

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            rolr-x86_64.xz
            rolr-x86_64.deb

  arch:
    runs-on: ubuntu-22.04
    container:
      image: archlinux
    permissions:
      contents: write
    steps:
      - name: install packages
        run: pacman -Syu base-devel rustup musl git sudo --noconfirm

      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup build user
        run: |
          useradd builder -m
          chown -R builder:builder .

      - name: install rust tools
        shell: sudo -u builder bash {0}
        run: |
          rustup default stable
          rustup target add x86_64-unknown-linux-musl
          cargo install cargo-arch

      - name: patch project version
        run: |
          tag=$(echo ${{ github.ref }} | grep -Po '(?<=^refs/tags/v).*')
          version=$tag+${GITHUB_SHA:0:8}
          sed -i "0,/version/{s/0.0.0/$version/}" Cargo.toml

      - name: package for arch
        run: |
          sudo -u builder cargo arch
          mv *.pkg.tar.zst rolr-x86_64.pkg.tar.zst

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: rolr-x86_64.pkg.tar.zst
