name: publish

on:
  push:
    tags: [ 'v*' ]

jobs:
  publish:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: install tools
        run: |
          sudo apt-get install musl-tools -y
          rustup target add x86_64-unknown-linux-musl
          cargo install cargo-deb

      - name: patch package version
        run: |
          tag=$(echo ${{ github.ref }} | grep -Po '(?<=^refs/tags/v).*')
          version=$tag+$(git rev-parse --short HEAD)
          sed -i "0,/version/{s/0.0.0/$version/}" Cargo.toml

      - name: build
        run: cargo build --release && cp target/x86_64-unknown-linux-musl/release/rolr ./rolr-x86_64 && xz rolr-x86_64

      - name: package deb
        run: cargo deb --target x86_64-unknown-linux-musl && cp target/x86_64-unknown-linux-musl/debian/rolr*.deb ./rolr-x86_64.deb

      - name: package for arch
        run: docker run --rm -v $(pwd):/source/rolr $(docker build -q . -f build/arch.Dockerfile --build-arg PUID=$(id -u) --build-arg PGID=$(id -g)) cargo arch && mv *.pkg.tar.zst rolr-x86_64.pkg.tar.zst

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            rolr-x86_64.xz
            rolr-x86_64.deb
            rolr-x86_64.pkg.tar.zst
